added Mady´s BBQ in Carnes
devschile/cuarentena pull request #36
Opened 2020-04-08 21:58 UTC by juanbrujo

2020-04-08 22:05 UTC, hectorpalmatellez commented on README.md
> +* [Mady´s BBQ](https://www.instagram.com/madysbbq03/)
```suggestion
* [Mady's BBQ](https://www.instagram.com/madysbbq03/)
```

2020-04-08 22:07 UTC, juanbrujo commented on README.md
> +* [Mady´s BBQ](https://www.instagram.com/madysbbq03/)
que sabis voh si no comes carne

2020-04-08 22:12 UTC, juanbrujo commented
que es esto, nunca lo habia visto: `[WhatsApp](https://wa.me/56941524136){:.skip-review}`

![Screen Shot 2020-04-08 at 6 09 39 PM](https://user-images.githubusercontent.com/362186/78838586-83341180-79c4-11ea-8a80-c06fc9e14011.png)

2020-04-08 22:46 UTC, alvaromeza commented
Los de costillasypunto los cacho, buenos ahumados 👌. Los otros ni idea.

2020-04-08 23:21 UTC, juanbrujo commented on README.md
> +* [Mady´s BBQ](https://www.instagram.com/madysbbq03/)
hecho vegan kl

2020-04-08 23:35 UTC, gmq commented
> que es esto, nunca lo habia visto: `[WhatsApp](https://wa.me/56941524136){:.skip-review}`
> 
> ![Screen Shot 2020-04-08 at 6 09 39 PM](https://user-images.githubusercontent.com/362186/78838586-83341180-79c4-11ea-8a80-c06fc9e14011.png)

Es para evitar que salgan estos comentarios en esos links, la idea es agregar esa clase cada vez que una tienda tenga más de un link.
<img width="154" alt="Screen Shot 2020-04-08 at 19 33 32" src="https://user-images.githubusercontent.com/472791/78843123-e8413480-79cf-11ea-99cd-4a9a9e514fad.png">

2020-04-08 23:39 UTC, gmq requested changes

2020-04-08 23:39 UTC, gmq commented on README.md
> +| [@veganvega_](https://www.instagram.com/veganvega_/) | [WhatsApp](https://wa.me/56941524136) | envío propio | quesos, dulces, pan y otros productos veganos |
```suggestion
| [@veganvega_](https://www.instagram.com/veganvega_/) | [WhatsApp](https://wa.me/56941524136){:.skip-review} | envío propio | quesos, dulces, pan y otros productos veganos |
```

2020-04-08 23:39 UTC, gmq commented on README.md
> +| [Supermarket Express](https://www.instagram.com/supermarket_express/) | [WhatsApp](https://wa.me/56972430386) |  Delivery gratis para Providencia, Ñuñoa, Las Condes, Santiago Centro, Chicureo. Entr
```suggestion
| [Supermarket Express](https://www.instagram.com/supermarket_express/) | [WhatsApp](https://wa.me/56972430386){:.skip-review}  |  Delivery gratis para Providencia, Ñuñoa, Las Condes, Santiago Centro, Chicureo. Entregas en menos de 60 minutos | Efectivo, Redcompra, Transferencia |
```

2020-04-09 01:57 UTC, hectorpalmatellez commented
con los cambios del :gmq: apruebo

2020-04-09 14:13 UTC, juanbrujo commented on README.md
> +| [@veganvega_](https://www.instagram.com/veganvega_/) | [WhatsApp](https://wa.me/56941524136) | envío propio | quesos, dulces, pan y otros productos veganos |
perfecto los vuelvo a agregar.

2020-04-09 20:12 UTC, juanbrujo commented
listeilor lords of the PR

2020-04-09 20:13 UTC, hectorpalmatellez approved these changes

2020-04-09 20:13 UTC, gmq approved these changes

2020-04-09 20:13 UTC, merged